# Generated by Django 6.0 on 2025-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
