# Generated by Django 6.0 on 2025-12-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_reserva_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='criada_em',
        ),
        migrations.AddField(
            model_name='reserva',
            name='expira_em',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 16, 46, 2, 202603, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('deferida', 'Deferida')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
