# Generated by Django 6.0 on 2025-12-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_data_reserva_criada_em_reserva_expira_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('deferida', 'Deferida'), ('CANCELADA', 'Cancelada')], default='pendente', max_length=10),
        ),
    ]
